# 파드 개수
replicaCount: 1

# PHP 앱 설정
phpApp:
  image: "larkracl/hybrid-dr-web:0516c2f3316d35e7c531e2e57413ebe7bc454b15"
  nodeSelector: "worker-node-1" # AWS로 갈 땐 이걸 지우거나 바꾸면 됨!

db:
  host: "mysql-service"   # AWS 팀원은 배포할 때 이 값을 RDS 엔드포인트 주소로 바꾸면 됨!
  user: "root"
  password: "password123!" # (주의: 실무에서는 Secret으로 빼지만, 지금은 테스트용으로 직관성 있게 갑니다)
  name: "dr_test_db"