# Cloudflare Quick Tunnel 파드

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-quick-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cf-tunnel
  template:
    metadata:
      labels:
        app: cf-tunnel
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-node-1 # 핵심!
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args: ["tunnel", "--no-autoupdate", "run"] # 실제 토큰으로 교체 필요
        env:
        - name: TUNNEL_TOKEN
          value: "eyJhIjoiYjY5NjJlNjhlOGIzOWI1YmNkNWUyYTJjMzJmYjQyNzIiLCJ0IjoiN2Q2YmYzMjAtYjc3OC00ZTZkLTg1NzMtNjVjZDA5MDhjZTcyIiwicyI6Ik0yTm1ObVE0WXpZdFpHRmhZeTAwTURkaUxXSXpNMlF0TkRSbFpXWTNZMll6TWpnNCJ9" # 실제 토큰으로 교체 필요